USE OnlineGradingSystem

CREATE TABLE Student(
Sid INT IDENTITY NOT NULL PRIMARY KEY,
FirstName VARCHAR(30) NOT NULL,
LastName VARCHAR(30) NOT NULL,
Major VARCHAR(50) NOT NULL,
Email VARCHAR(30) NULL,
Telephone VARCHAR(30) NULL,
Birth DATE NULL,
Addr VARCHAR(100) NULL,
UserName VARCHAR(30) UNIQUE NOT NULL,
Pwd VARCHAR(30) NOT NULL
)
GO

CREATE TABLE Teacher(
Tid INT IDENTITY NOT NULL PRIMARY KEY,
FirstName VARCHAR(30) NOT NULL,
LastName VARCHAR(30) NOT NULL,
Email VARCHAR(30) NULL,
Addr VARCHAR(100) NULL,
Telephone VARCHAR(30) NULL,
Birth DATE NULL,
UserName VARCHAR(30) UNIQUE NOT NULL,
Pwd VARCHAR(30) NOT NULL
)
GO

CREATE TABLE Course(
Cid INT IDENTITY NOT NULL PRIMARY KEY,
Name VARCHAR(30) NOT NULL,
Credit INT NOT NULL,
Tid INT FOREIGN KEY REFERENCES Teacher(Tid) NULL
)
GO

CREATE TABLE Assignment(
Aid INT IDENTITY NOT NULL PRIMARY KEY,
Title VARCHAR(255) NOT NULL,
Comment VARCHAR(255) NULL,
Tid INT NULL FOREIGN KEY REFERENCES Teacher(Tid),
Cid INT NOT NULL FOREIGN KEY REFERENCES Course(Cid) ON DELETE CASCADE
)

CREATE TABLE Question(
Qid INT IDENTITY NOT NULL PRIMARY KEY,
Title VARCHAR(255) NOT NULL,
Weight INT NOT NULL,
Aid INT NOT NULL FOREIGN KEY REFERENCES Assignment(Aid) ON DELETE CASCADE,
Cid INT NOT NULL FOREIGN KEY REFERENCES Course(Cid)
)

CREATE TABLE Answer(
Aid INT NOT NULL FOREIGN KEY REFERENCES Assignment(Aid),
Qid INT NOT NULL FOREIGN KEY REFERENCES Question(Qid),
Mark DECIMAL(10,5) NULL,
Comment VARCHAR(255) NULL,
Answer VARCHAR(255) NULL,
Tid INT NULL FOREIGN KEY REFERENCES Teacher(Tid),
Sid INT NULL FOREIGN KEY REFERENCES Student(Sid)
)

CREATE TABLE StudentTakeCourse(
Sid INT FOREIGN KEY REFERENCES Student(Sid) NOT NULL,
Cid INT FOREIGN KEY REFERENCES Course(Cid) NOT NULL
)